### ISSUE TITLE
如何设置页面的宽度

### ISSUE THREAD

**Issue by zkf0261** [s-theo/lumen#240]
如何设置页面的宽度

**Comment by s-theo** [comment]
```css
:root {
  --vp-layout-max-width: 1440px;
}
```

修改为想要的参数即可
